print("Welcome to the tip calculator.")
bill = float(input("What was the total bill? $"))
tip = int(input("What percent of tip would you like to give? 10, 12, or 15? "))
split = int(input("How many people to split the bill? "))
result = "{:.2f}".format((bill / split) * (1 + tip/100))
print(f"Each person should pay : ${result}")